# ============================================================
# CogniGrid Backend — Flask API
# ============================================================
# Receives game session data from the React frontend and
# returns MMSE prediction + cognitive zone classification.
#
# Usage:
#   pip install flask flask-cors
#   python app.py
#
# Make sure scaler.pkl, xgb_model.pkl, model_meta.pkl are
# in the same directory (generated by data_processing_v5.py)
# ============================================================

from flask import Flask, request, jsonify
from flask_cors import CORS
import numpy as np
import pandas as pd
import joblib
import os

app = Flask(__name__)
CORS(app)

# ── Load model artifacts ──────────────────────────────────
BASE = os.path.dirname(os.path.abspath(__file__))

try:
    scaler  = joblib.load(os.path.join(BASE, 'scaler.pkl'))
    model   = joblib.load(os.path.join(BASE, 'xgb_model.pkl'))
    meta    = joblib.load(os.path.join(BASE, 'model_meta.pkl'))
    X_COLS  = meta['X_cols']
    MRI     = meta['mri_means']
    print("✅ Model artifacts loaded successfully.")
except Exception as e:
    print(f"⚠  Could not load model artifacts: {e}")
    scaler = model = None
    X_COLS = []
    MRI    = {'Ventricles': 0, 'WholeBrain': 0, 'ICV': 1}

# ── Clinical anchors (from data_processing_v5.py) ────────
ANCHORS = {
    'RAVLT_immediate': [41.0, 21.0,  6.0],
    'ADAS13':          [12.0, 28.0, 52.0],
    'CDRSB':           [ 1.0,  3.9,  9.5],
    'FAQ':             [ 2.3, 11.4, 22.0],
}

BAND_CONFIG = [
    (25.5, 30.0,  "Normal",       "Clear",      "Normal cognition",
     "No signs of cognitive decline detected."),
    (23.0, 25.5,  "Normal",       "Borderline", "Borderline Normal / MCI",
     "Score is near the Normal/MCI boundary. Consider retesting or clinical follow-up."),
    (18.5, 23.0,  "MCI",          "Clear",      "Mild Cognitive Impairment (MCI)",
     "Signs consistent with MCI. Recommend clinical assessment."),
    (16.5, 18.5,  "MCI",          "Borderline", "Borderline MCI / Alzheimer's",
     "Score is near the MCI/Alzheimer's boundary. Clinical evaluation strongly advised."),
    ( 0.0, 16.5,  "Alzheimer's",  "Clear",      "Consistent with Alzheimer's",
     "Score suggests significant cognitive impairment. Urgent clinical referral recommended."),
]


def interp_clinical(impairment: float) -> dict:
    t = float(np.clip(impairment, 0, 1))
    result = {}
    for feat, (v_norm, v_mci, v_alz) in ANCHORS.items():
        if t <= 0.5:
            val = v_norm + (v_mci - v_norm) * (t / 0.5)
        else:
            val = v_mci  + (v_alz - v_mci)  * ((t - 0.5) / 0.5)
        result[feat] = round(float(val), 2)
    return result


def game_to_clinical(data: dict) -> dict:
    acc      = data['accuracy']       / 100
    mistakes = data['mistakes']       / max(data['max_mistakes'], 1)
    time     = data['time_taken']     / max(data['max_time'], 1)
    learning = data['learning_score'] / max(data['max_learning'], 1)
    impairment = (
        0.35 * (1 - acc)  +
        0.30 * mistakes   +
        0.20 * time       +
        0.15 * (1 - learning)
    )
    return interp_clinical(impairment), round(float(impairment), 3)


def classify_with_confidence(mmse: float) -> dict:
    for lo, hi, zone, confidence, band_label, advice in BAND_CONFIG:
        if lo <= mmse < hi:
            return {'zone': zone, 'confidence': confidence,
                    'band': band_label, 'advice': advice}
    return {'zone': 'Normal', 'confidence': 'Clear',
            'band': 'Normal cognition',
            'advice': 'No signs of cognitive decline detected.'}


def prepare_input(data: dict, clinical: dict) -> np.ndarray:
    full_input = {
        'AGE':             data.get('AGE', 65),
        'APOE4':           data.get('APOE4', 0),
        'PTEDUCAT':        data.get('PTEDUCAT', 12),
        'Ventricles':      MRI['Ventricles'],
        'WholeBrain':      MRI['WholeBrain'],
        'ICV':             MRI['ICV'],
        **clinical,
    }
    df = pd.DataFrame([full_input])
    # engineered features
    df['BrainHealthyRatio'] = df['WholeBrain'] / df['ICV']
    df['VentricularRatio']  = df['Ventricles']  / df['ICV']
    df['AtrophyIndex']      = df['Ventricles']  / df['WholeBrain']
    df = df.reindex(columns=X_COLS, fill_value=0)
    return scaler.transform(df)


# ── Routes ────────────────────────────────────────────────

@app.route('/api/health', methods=['GET'])
def health():
    return jsonify({
        'status': 'ok',
        'model_loaded': model is not None,
    })


@app.route('/api/predict', methods=['POST'])
def predict():
    if model is None:
        return jsonify({'error': 'Model not loaded. Run data_processing_v5.py first.'}), 503

    data = request.get_json()
    if not data:
        return jsonify({'error': 'No JSON body received'}), 400

    # Validate required fields
    required = ['accuracy', 'mistakes', 'max_mistakes', 'time_taken', 'max_time',
                'learning_score', 'max_learning']
    missing = [f for f in required if f not in data]
    if missing:
        return jsonify({'error': f'Missing fields: {missing}'}), 400

    try:
        clinical, impairment = game_to_clinical(data)
        inp  = prepare_input(data, clinical)
        mmse = float(np.clip(model.predict(inp)[0], 0, 30))

        result = classify_with_confidence(mmse)
        result.update({
            'mmse':        round(mmse, 2),
            'impairment':  impairment,
            'clinical':    clinical,
            # Echo back aggregated game stats for frontend display
            'game_stats': {
                'accuracy':       data.get('accuracy'),
                'mistakes':       data.get('mistakes'),
                'time_taken':     data.get('time_taken'),
                'learning_score': data.get('learning_score'),
                'levels_played':  data.get('levels_played', 1),
            },
            'profile': {
                'age':      data.get('AGE', 65),
                'apoe4':    data.get('APOE4', 0),
                'pteducat': data.get('PTEDUCAT', 12),
            }
        })
        return jsonify(result)

    except Exception as e:
        return jsonify({'error': str(e)}), 500


if __name__ == '__main__':
    print("CogniGrid backend running on http://localhost:5000")
    app.run(debug=True, port=5000)
